{
 "title": "Painel Mesa-Labirinto",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "100ms",
 "panels": [
  {
   "title": "Inclinação (Pitch)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"MesaLabirinto\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mesa_status\")\n  |> filter(fn: (r) => r[\"origem\"] == \"esp32_hardware_real\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pitch\")\n  |> aggregateWindow(every: 100ms, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ \n      r with _value: r._value + 11.5 \n  }))"
    }
   ]
  },
  {
   "title": "Inclinação (Roll)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"MesaLabirinto\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mesa_status\")\n  |> filter(fn: (r) => r[\"origem\"] == \"esp32_hardware_real\")\n  |> filter(fn: (r) => r[\"_field\"] == \"roll\")\n  |> aggregateWindow(every: 50ms, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({\n      r with _value: \n        if (r._value - 170.0) < -180.0 then (r._value - 170.0) + 360.0\n        else (r._value - 170.0)\n    }))"
    }
   ]
  },
  {
   "title": "Atuadores (Motores)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"MesaLabirinto\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mesa_status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"servo_x\" or r[\"_field\"] == \"servo_y\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Input Joystick",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"MesaLabirinto\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mesa_status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"joy_x\" or r[\"_field\"] == \"joy_y\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Posição do Joystick",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"MesaLabirinto\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mesa_status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"joy_x\" or r[\"_field\"] == \"joy_y\")\n  |> aggregateWindow(every: 100ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Inclinação da Mesa (Giroscópio)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"MesaLabirinto\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mesa_status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pitch\" or r[\"_field\"] == \"roll\")\n  |> aggregateWindow(every: 100ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}